### ISSUE TITLE
Run in linux

### ISSUE THREAD

**Issue by Cuervocartoon** [zmoon/screen3#4]
Hi there

I'm wondering how can I run in linux OS. I tried using 

> screen3.build()

But still needs .exe in order to run.

Do you think that's possible?

Thnaks in advanced

**Comment by zmoon** [comment]
Hi @Cuervocartoon , what error did you get with `screen3.build()`? It should work if you first `screen3.download()`, provided you have `patch` and `gfortran` available.

**Comment by Cuervocartoon** [comment]
Hi zmoon, thanks for the response. Actually the screen3.build() runs well, but then when I call

screen.run(parameters)

I'm getting the error saying that there's is not exe, and when I call:

screen.run(parameters, exe="path")

Another error prompts appear.

How can I say to screen.run works for Linux?

Pd. Actually I'm trying to run in Google colab.

Thank you again.

**Comment by zmoon** [comment]
I just tried on colab and didn't have issue. If the build is successful the executable should be at `./src/SCREEN3.exe` by default.

<details>

![image](https://github.com/zmoon/screen3/assets/15079414/fb4aaf85-fdc1-4b35-83fd-1d65553d0f0a)
</details>

**Comment by Cuervocartoon** [comment]
Perfect, I'll check the my routes.

Thanks for your guide.

**Comment by zmoon** [comment]
Feel free to reopen this and share error message if you have more issues.
